In [1]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/AI-Powered-Supply-Chain-Analytics/data/processed/DataCoSupplyChainDataset_Clean.csv"
)

In [2]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,COMPLETE,NaN,1360,73,NaN,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,PENDING,NaN,1360,73,NaN,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,CLOSED,NaN,1360,73,NaN,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,COMPLETE,NaN,1360,73,NaN,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,PENDING_PAYMENT,NaN,1360,73,NaN,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class

In [3]:
df["order date (DateOrders)"] = pd.to_datetime(df["order date (DateOrders)"])
df["shipping date (DateOrders)"] = pd.to_datetime(df["shipping date (DateOrders)"])

In [4]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,COMPLETE,NaN,1360,73,NaN,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,PENDING,NaN,1360,73,NaN,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,CLOSED,NaN,1360,73,NaN,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,COMPLETE,NaN,1360,73,NaN,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,PENDING_PAYMENT,NaN,1360,73,NaN,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class

### Feature1:Shipping Delay

In [12]:
# Create Shipping Delay feature
df["Shipping Delay"] = (
    df["Days for shipping (real)"] -
    df["Days for shipment (scheduled)"]
)

In [13]:
df[
    [
        "Days for shipping (real)",
        "Days for shipment (scheduled)",
        "Shipping Delay"
    ]
].head(10)

   Days for shipping (real)  Days for shipment (scheduled)  Shipping Delay
0                         3                              4              -1
1                         5                              4               1
2                         4                              4               0
3                         3                              4              -1
4                         2                              4              -2
5                         6                              4               2
6                         2                              1               1
7                         2                              1               1
8                         3                              2               1
9                         2                              1               1

In [9]:
# Create Order Month feature
df["Order Month"] = df["order date (DateOrders)"].dt.month_name()

###Feature2:Order Month

In [11]:
df[
    [
        "order date (DateOrders)",
        "Order Month"
    ]
].head(10)

  order date (DateOrders) Order Month
0     2018-01-31 22:56:00     January
1     2018-01-13 12:27:00     January
2     2018-01-13 12:06:00     January
3     2018-01-13 11:45:00     January
4     2018-01-13 11:24:00     January
5     2018-01-13 11:03:00     January
6     2018-01-13 10:42:00     January
7     2018-01-13 10:21:00     January
8     2018-01-13 10:00:00     January
9     2018-01-13 09:39:00     January

###Feature3:Order Month Number

In [14]:
# Create Order Month Number
df["Order Month Number"] = df["order date (DateOrders)"].dt.month

In [15]:
df[
    [
        "order date (DateOrders)",
        "Order Month",
        "Order Month Number"
    ]
].head(10)

  order date (DateOrders) Order Month  Order Month Number
0     2018-01-31 22:56:00     January                   1
1     2018-01-13 12:27:00     January                   1
2     2018-01-13 12:06:00     January                   1
3     2018-01-13 11:45:00     January                   1
4     2018-01-13 11:24:00     January                   1
5     2018-01-13 11:03:00     January                   1
6     2018-01-13 10:42:00     January                   1
7     2018-01-13 10:21:00     January                   1
8     2018-01-13 10:00:00     January                   1
9     2018-01-13 09:39:00     January                   1

###Feature 4: Order Quarter

In [16]:
# Create Order Quarter
df["Order Quarter"] = df["order date (DateOrders)"].dt.quarter

In [17]:
df[
    [
        "order date (DateOrders)",
        "Order Quarter"
    ]
].head(10)

  order date (DateOrders)  Order Quarter
0     2018-01-31 22:56:00              1
1     2018-01-13 12:27:00              1
2     2018-01-13 12:06:00              1
3     2018-01-13 11:45:00              1
4     2018-01-13 11:24:00              1
5     2018-01-13 11:03:00              1
6     2018-01-13 10:42:00              1
7     2018-01-13 10:21:00              1
8     2018-01-13 10:00:00              1
9     2018-01-13 09:39:00              1

###Feature 5: Order Year

In [18]:
# Create Order Year
df["Order Year"] = df["order date (DateOrders)"].dt.year

In [19]:
df[
    [
        "order date (DateOrders)",
        "Order Year"
    ]
].head()

  order date (DateOrders)  Order Year
0     2018-01-31 22:56:00        2018
1     2018-01-13 12:27:00        2018
2     2018-01-13 12:06:00        2018
3     2018-01-13 11:45:00        2018
4     2018-01-13 11:24:00        2018

###Feature 6: Order Day Name

In [20]:
# Create Order Day
df["Order Day"] = df["order date (DateOrders)"].dt.day_name()

In [21]:
df[
    [
        "order date (DateOrders)",
        "Order Day"
    ]
].head()

  order date (DateOrders)  Order Day
0     2018-01-31 22:56:00  Wednesday
1     2018-01-13 12:27:00   Saturday
2     2018-01-13 12:06:00   Saturday
3     2018-01-13 11:45:00   Saturday
4     2018-01-13 11:24:00   Saturday

###Feature 7: Day Type

In [22]:
# Create Day Type feature
df["Day Type"] = df["Order Day"].apply(
    lambda x: "Weekend" if x in ["Saturday", "Sunday"] else "Weekday"
)

In [23]:
df[
    [
        "Order Day",
        "Day Type"
    ]
].head(10)

   Order Day Day Type
0  Wednesday  Weekday
1   Saturday  Weekend
2   Saturday  Weekend
3   Saturday  Weekend
4   Saturday  Weekend
5   Saturday  Weekend
6   Saturday  Weekend
7   Saturday  Weekend
8   Saturday  Weekend
9   Saturday  Weekend

###feature8:Profit Margin

In [24]:
# Create Profit Margin feature
df["Profit Margin"] = (
    df["Order Profit Per Order"] / df["Sales"]
) * 100

In [25]:
df[
    [
        "Sales",
        "Order Profit Per Order",
        "Profit Margin"
    ]
].head(10)

    Sales  Order Profit Per Order  Profit Margin
0  327.75               91.250000      27.841342
1  327.75             -249.089996     -75.999999
2  327.75             -247.779999     -75.600305
3  327.75               22.860001       6.974829
4  327.75              134.210007      40.948896
5  327.75               18.580000       5.668955
6  327.75               95.180000      29.040427
7  327.75               68.430000      20.878719
8  327.75              133.720001      40.799390
9  327.75              132.149994      40.320364

In [26]:
df.to_csv(
    "/content/drive/MyDrive/AI-Powered-Supply-Chain-Analytics/data/processed/DataCoSupplyChainDataset_FeatureEngineered.csv",
    index=False
)